### YamlMime:Yaml
ms.openlocfilehash: 6531a2483b7a8ba85443a5d5c2b11c0bebeb7525
ms.sourcegitcommit: 27a4afc732f8733e6022af2a58d01af5ae83545b
ms.translationtype: HT
ms.contentlocale: fr-FR
ms.lasthandoff: 03/23/2022
ms.locfileid: "140813683"
name: IceCreamRatings-Java
on:
  push:
    branches:
    - master
jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
    - name: Consulter GitHub Actions
      uses: actions/checkout@master
    - name: Se connecter via Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Configurer Java 1.8.x
      uses: actions/setup-java@v1
      with:
        java-version: 1.8.x
    - name: Exécuter mvn
      shell: pwsh
      run: >
        mvn clean package

        mvn azure-functions:package
    - name: Exécuter une action Azure Functions
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: PLEASE_REPLACE_THIS_WITH_YOUR_FUNCTION_APP_NAME
        package: ./target/azure-functions/POM_FUNCTION_APP_NAME
